# Site wide configuration

title:            MosquitOS
locale:           en_US
url:              http://localhost:4000


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Kyle Moore
  avatar: bio-photo.jpg
  bio: "A recent graduate of Stanford University who enjoys rock climbing, cycling, and writing terrible operating systems."
  email: kmmoore@alumni.stanford.edu
  disqus-shortname: mosquitos
  twitter: #username
  facebook: #username
  google:
    plus:
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: kmmoore
  stackoverflow: http://stackoverflow.com/users/100112/kyle
  linkedin: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
